export function taskToMarkdown(task: import('../types/task').Task): string {
  const status = task.status === 'done' ? '[x]' : '[ ]';
  const priority = task.priority === 1 ? '🔴' : task.priority === 2 ? '🟡' : '🟢';
  let md = `- ${status} ${priority} **${task.title}**`;
  if (task.estimated_min) md += ` _(est. ${task.estimated_min}m)_`;
  if (task.actual_min) md += ` _(actual: ${task.actual_min}m)_`;
  if (task.notes) md += `\n  > ${task.notes.replace(/\n/g, '\n  > ')}`;
  return md;
}

export function reportToMarkdown(
  report: import('../types/report').DailyReport,
  tasks: import('../types/task').Task[],
  date: string
): string {
  const completionRate = report.tasks_planned > 0
    ? Math.round((report.tasks_completed / report.tasks_planned) * 100)
    : 0;

  const formatTaskList = (list: import('../types/task').Task[]) =>
    list.map(taskToMarkdown).join('\n');

  return `# Daily Report — ${date}

## Summary
- Tasks completed: ${report.tasks_completed}/${report.tasks_planned} (${completionRate}%)
- Focus time: ${formatDuration(report.total_focus_min)}
- Skipped: ${report.tasks_skipped} | Carried over: ${report.tasks_carried}

## Tasks
${tasks.length > 0 ? formatTaskList(tasks) : '_No tasks_'}

${report.ai_reflection ? `## AI Reflection\n${report.ai_reflection}` : ''}

_Generated by Daily Planner_
`;
}

function formatDuration(minutes: number): string {
  if (minutes < 60) return `${minutes}m`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m > 0 ? `${h}h ${m}m` : `${h}h`;
}
