/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', "'SF Pro Text'", "'Inter'", 'system-ui', 'sans-serif'],
      },
      colors: {
        // macOS-inspired muted palette
        surface: {
          DEFAULT: '#FFFFFF',
          subtle: '#F5F5F7',
          overlay: 'rgba(255,255,255,0.85)',
        },
        border: {
          DEFAULT: '#D2D2D7',
          subtle: '#E8E8ED',
        },
        text: {
          primary: '#1D1D1F',
          secondary: '#6E6E73',
          tertiary: '#AEAEB2',
        },
        accent: {
          DEFAULT: '#0071E3',
          hover: '#0077ED',
          soft: '#E3F0FF',
        },
        success: {
          DEFAULT: '#34C759',
          soft: '#E8F9EC',
        },
        warning: {
          DEFAULT: '#FF9500',
          soft: '#FFF3E0',
        },
        danger: {
          DEFAULT: '#FF3B30',
          soft: '#FFEEEC',
        },
        priority: {
          high: '#FF3B30',
          medium: '#FF9500',
          low: '#34C759',
        },
        status: {
          todo: '#6E6E73',
          improved: '#5E5CE6',
          planned: '#0071E3',
          in_progress: '#FF9500',
          review: '#34C759',
        },
        // Keep legacy synq tokens for backward compatibility with existing components
        'synq-bg-app':              '#F5F5F7',
        'synq-bg-surface':          '#FFFFFF',
        'synq-bg-surface-2':        '#F5F5F7',
        'synq-bg-surface-3':        '#E8E8ED',
        'synq-text-primary':        '#1D1D1F',
        'synq-text-secondary':      '#6E6E73',
        'synq-text-tertiary':       '#AEAEB2',
        'synq-text-disabled':       '#AEAEB2',
        'synq-border-subtle':       '#E8E8ED',
        'synq-border-default':      '#D2D2D7',
        'synq-border-strong':       '#AEAEB2',
        'synq-accent':              '#0071E3',
        'synq-accent-hover':        '#0077ED',
        'synq-accent-active':       '#005BBB',
        'synq-accent-soft':         '#E3F0FF',
        // Synq dark mode tokens (updated to macOS dark palette)
        'synq-dark-bg-app':         '#1C1C1E',
        'synq-dark-bg-surface':     '#2C2C2E',
        'synq-dark-bg-surface-2':   '#3A3A3C',
        'synq-dark-bg-surface-3':   '#48484A',
        'synq-dark-text-primary':   '#F5F5F7',
        'synq-dark-text-secondary': '#AEAEB2',
        'synq-dark-text-tertiary':  '#6E6E73',
        'synq-dark-text-disabled':  '#48484A',
        'synq-dark-border-subtle':  '#3A3A3C',
        'synq-dark-border-default': '#48484A',
        'synq-dark-border-strong':  '#6E6E73',
        'synq-dark-accent':         '#409CFF',
        'synq-dark-accent-hover':   '#5AABFF',
        'synq-dark-accent-active':  '#0071E3',
        // State colors
        'synq-success':             '#34C759',
        'synq-success-soft':        '#E8F9EC',
        'synq-warning':             '#FF9500',
        'synq-warning-soft':        '#FFF3E0',
        'synq-danger':              '#FF3B30',
        'synq-danger-soft':         '#FFEEEC',
        'synq-info':                '#0071E3',
        'synq-info-soft':           '#E3F0FF',
      },
      borderRadius: {
        DEFAULT: '10px',
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '18px',
        '2xl': '22px',
        // Keep legacy synq tokens
        'synq-sm': '6px',
        'synq-md': '10px',
        'synq-lg': '14px',
        'synq-xl': '18px',
        'synq-pill': '999px',
      },
      boxShadow: {
        'mac':       '0 1px 3px rgba(0,0,0,0.08), 0 4px 12px rgba(0,0,0,0.06)',
        'mac-lg':    '0 4px 20px rgba(0,0,0,0.08), 0 8px 40px rgba(0,0,0,0.06)',
        'mac-modal': '0 20px 60px rgba(0,0,0,0.15), 0 4px 20px rgba(0,0,0,0.08)',
        // Keep legacy synq tokens
        'synq-sm':      '0 1px 3px rgba(0,0,0,0.08), 0 4px 12px rgba(0,0,0,0.06)',
        'synq-md':      '0 4px 20px rgba(0,0,0,0.08), 0 8px 40px rgba(0,0,0,0.06)',
        'synq-sm-dark': '0 1px 3px rgba(0,0,0,0.20), 0 4px 12px rgba(0,0,0,0.16)',
        'synq-md-dark': '0 4px 20px rgba(0,0,0,0.28), 0 8px 40px rgba(0,0,0,0.22)',
      },
      backdropBlur: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '20px',
      },
      fontSize: {
        'synq-display': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'synq-h1':      ['28px', { lineHeight: '36px', letterSpacing: '-0.02em' }],
        'synq-h2':      ['24px', { lineHeight: '32px', letterSpacing: '-0.02em' }],
        'synq-h3':      ['20px', { lineHeight: '28px', letterSpacing: '-0.02em' }],
        'synq-title':   ['18px', { lineHeight: '26px' }],
        'synq-body':    ['16px', { lineHeight: '24px' }],
        'synq-body-sm': ['14px', { lineHeight: '20px' }],
        'synq-caption': ['12px', { lineHeight: '16px', letterSpacing: '0.01em' }],
      },
    },
  },
  plugins: [],
}
