/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Vegr light mode tokens
        'vegr-bg-app':              '#F8FAFC',
        'vegr-bg-surface':          '#FFFFFF',
        'vegr-bg-surface-2':        '#F1F5F9',
        'vegr-bg-surface-3':        '#E2E8F0',
        'vegr-text-primary':        '#111827',
        'vegr-text-secondary':      '#475569',
        'vegr-text-tertiary':       '#64748B',
        'vegr-text-disabled':       '#94A3B8',
        'vegr-border-subtle':       '#E2E8F0',
        'vegr-border-default':      '#CBD5E1',
        'vegr-border-strong':       '#94A3B8',
        'vegr-accent':              '#60A5FA',
        'vegr-accent-hover':        '#3B82F6',
        'vegr-accent-active':       '#2563EB',
        'vegr-accent-soft':         '#DBEAFE',
        // Vegr dark mode tokens
        'vegr-dark-bg-app':         '#0F172A',
        'vegr-dark-bg-surface':     '#111827',
        'vegr-dark-bg-surface-2':   '#1E293B',
        'vegr-dark-bg-surface-3':   '#334155',
        'vegr-dark-text-primary':   '#E5E7EB',
        'vegr-dark-text-secondary': '#CBD5E1',
        'vegr-dark-text-tertiary':  '#94A3B8',
        'vegr-dark-text-disabled':  '#64748B',
        'vegr-dark-border-subtle':  '#1E293B',
        'vegr-dark-border-default': '#334155',
        'vegr-dark-border-strong':  '#475569',
        'vegr-dark-accent':         '#7DD3FC',
        'vegr-dark-accent-hover':   '#38BDF8',
        'vegr-dark-accent-active':  '#0EA5E9',
        // State colors
        'vegr-success':             '#2F6B5F',
        'vegr-success-soft':        '#ECFDF5',
        'vegr-warning':             '#C28A3D',
        'vegr-warning-soft':        '#FEF3C7',
        'vegr-danger':              '#B4534B',
        'vegr-danger-soft':         '#FEE2E2',
        'vegr-info':                '#4F7C82',
        'vegr-info-soft':           '#E0F2FE',
      },
      borderRadius: {
        'vegr-sm': '10px',
        'vegr-md': '12px',
        'vegr-lg': '14px',
        'vegr-xl': '18px',
        'vegr-pill': '999px',
      },
      boxShadow: {
        'vegr-sm': '0 1px 2px rgba(15, 23, 42, 0.04)',
        'vegr-md': '0 4px 12px rgba(15, 23, 42, 0.06)',
        'vegr-sm-dark': '0 1px 2px rgba(2, 6, 23, 0.20)',
        'vegr-md-dark': '0 4px 12px rgba(2, 6, 23, 0.28)',
      },
      fontSize: {
        'vegr-display': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'vegr-h1':      ['28px', { lineHeight: '36px', letterSpacing: '-0.02em' }],
        'vegr-h2':      ['24px', { lineHeight: '32px', letterSpacing: '-0.02em' }],
        'vegr-h3':      ['20px', { lineHeight: '28px', letterSpacing: '-0.02em' }],
        'vegr-title':   ['18px', { lineHeight: '26px' }],
        'vegr-body':    ['16px', { lineHeight: '24px' }],
        'vegr-body-sm': ['14px', { lineHeight: '20px' }],
        'vegr-caption': ['12px', { lineHeight: '16px', letterSpacing: '0.01em' }],
      },
    },
  },
  plugins: [],
}

